<head>
    <base href="<?php echo(BASE_URL)?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/index.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD Marcas</title>
</head>
<body>
    <?php include_once 'templates/header.phtml';?>
    <main>
        <form action="agregarMarca" method="post">
            <div class="row">
                <div class="col-5 ">
                    <div class="form-group">
                        <label class="m-1">Nombre de la categoria:</label>
                        <input required name="Nombre_categoria" type="text" class="form-control m-1">
                        <label class="m-1">Descripción:</label>
                        <input required name="Descripcion_categoria" type="text" class="form-control m-1">
                        <label for="">Pais:</label>
                        <input required name="Pais_origen" type="text" class="form-control m-1">
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Guardar</button>
        </form>
        <?php
        foreach ($marcas as $marca) : ?>
                        <li class="list-group-item item-rutina">
                            <div class="m-2"></div>
                                <b>
                                    <?=$marca->Nombre?>
                                </b>
                            </div>
                            <div class="actions col">
                                <a href="eliminar_marca/<?=$marca->ID ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                                <a href="detallar_marca/<?=$marca->ID ?>" class="btn btn-warning"> Mostrar más</a>
                            </div>
                        </li>
        <?php endforeach;?>
        <?php include_once 'templates/footer.phtml';?>
    </main>
