<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?php echo(BASE_URL)?>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="css/index.css">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CRUD Productos</title>
    </head>
    <body>
    <?php include_once 'templates/header.phtml';?>
        <img id="img-suplements" src="https://www.demusculos.com/shop/c/10-category_default/suplementos.jpg" alt="" srcset="">
            <h2>Creatinas</h2>
                <p>Previenen la fatiga muscular, aumentan el rendimiento. Ideales para todo tipo de deportes, hombres y mujeres que buscan más rendimiento a la hora de entrenar y menos fatiga.</p>
            <h2>Aminoácidos</h2>
                <p>Potencian la recuperación del músculo, permiten alcanzar tus objetivos más rápidamente.</p>
            <h2>Proteínas</h2>
                <p>Las proteínas o Whey Protein son excelentes recuperadores y aumentadores de masa muscular. Mejoran el rendimiento y son apta para todo tipo de deportes. Las proteínas están dentro de los suplementos naturales más utilizados en el deporte.</p>
    <?php include_once 'templates/footer.phtml';?>