<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/index.css">
    <title>product</title>
</head>

<body>
    <?php include 'templates/header.phtml';?>
    <main>
        <div>
            <img src=<?=$product->Img?> alt='Imagen Producto'>
        </div>
        <div>
            <p> 
                <?=$product->Nombre?>, $ <?=$product->Precio?>, <?=$product->Peso?>, <?=$product->Categoria?>. 
            </p>
            <p> <?=$product->Descripcion?></p>
        </div>
    </main>
    <?php include 'templates/footer.phtml';?>