<!DOCTYPE html>
        <html lang="en">
        <head>
            <base href="<?php echo(BASE_URL)?>">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
            <link rel="stylesheet" href="css/index.css">
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Productos</title>
        </head>
        <body>
            <?php include_once 'templates/header.phtml';?>
                <h1>Productos</h1>
                <div class="container-product">
                    <div class="sidebar">
                        <h3><a href=""> Todos Los Productos</a></h3>
                        <ul class="list-categories">
                            <li class="list-item">Marca</li>
                            <ul class="list-show">
                                    <?php foreach($brands as $brand):?>
                                        <li class="list-inside"><a class="categories-link" href="productos/<?=$brand->ID?>"><?=$brand->Nombre?></a></li>
                                    <?php endforeach;?>
                            </ul>
                            <li class="list-item ">Origen</li>
                                <ul class="list-show">
                                    <li class="list-inside"><a class="categories-link" href="productos/argentina">Argentina</a></li>
                                    <li class="list-inside"><a class="categories-link" href="productos/eeuu">Estados Unidos</a></li>
                                </ul>
                            <li class="list-item" >Categoria</li>
                                <ul class="list-show">
                                    <li class="list-inside"><a class="categories-link" href="productos/creatina">Creatina</a></li>
                                    <li class="list-inside"><a class="categories-link" href="productos/proteina">Proteina</a></li>
                                    <li class="list-inside"><a class="categories-link" href="productos/aminoacidos">Aminoacidos</a></li>
                                </ul>
                        </ul>
                    </div>
                    <div class="show-products">
                        <?php foreach ($products as $product): ?>
                            <div class='target-product'>
                                <a href='product/<?=$product->ID?>'>
                                    <img class='target-img' src='<?=$product->Img?>' alt='Imagen Producto'>
                                    <h5 class='target-name'><?=$product->Nombre?></h5>
                                    <p><?=$product->Precio?></p>
                                </a>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
            <?php require_once 'templates/footer.phtml'?>        