<header>
    <img id="logo" src="https://scontent.fmdq6-1.fna.fbcdn.net/v/t1.18169-9/10320274_1409681205983956_8914705173760556618_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=be3454&_nc_eui2=AeEFRrxmr3S4zq-T_YV7nC62hRPVLymoj5uFE9UvKaiPm01ucFLrtXtYt2glosvGFYY&_nc_ohc=dHMx9vEb3FMAX8epzoj&_nc_ht=scontent.fmdq6-1.fna&oh=00_AfD680cODGtusk-bH4ebsaqRiohwdUnNdSvQyGym2IUT2Q&oe=654F5EF3" alt="Logo Pope Gym" srcset="">
    <nav>
        <ul>
            <li><a href="home" class="nav-button">Home</a></li>
            <li><a href="productos" class="nav-button">Productos</a></li>
            <li><a href="rutinas" class="nav-button">Rutinas</a></li>
            <li><a href="login" class="nav-button">Iniciar Sesion</a></li>
        </ul>
    </nav>
</header>

    