<!DOCTYPE html>
        <html lang="en">
        <head>
            <base href="<?php echo(BASE_URL)?>">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
            <link rel="stylesheet" href="css/index.css">
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>CRUD Productos</title>
        </head>
        <body>
            <?php include_once 'templates/header.phtml' ?>
                <h1>Agregar Suplementos al catalogo del gimnasio.</h1>
                <form id= "form" action="agregar" method="post">
                    <div class="row">
                        <div class="col-5 ">
                            <div class="form-group">
                            <label class="m-1">Nombre del producto:</label>
                            <input required name="Nombre" type="text" class="form-control m-1">
                            <label class="m-1">Descripción:</label>
                            <input required name="Descripcion" type="text" class="form-control m-1">
                            
                            <label class="m-1">Precio:</label>
                            <input required name="Precio" type="text" class="form-control m-1">
                            <label for="">Peso:</label>
                            <input required name="Peso" type="text" class="form-control m-1">
                            <label for="">Categoría:</label>
                                <select name="Categoria" id="">
                                    <option value="creatina">Creatina</option>
                                    <option value="proteina">Proteina</option>
                                    <option value="aminoacidos">Aminoacidos</option>
                                </select>
                            <label for="">Marca</label>
                                <select name="Marca" id="">
                                    <option value="1">Generation Fit</option>
                                    <option value="2">Gentech</option>
                                    <option value="3">Optimum Nutrition</option>
                                    <option value="4">Star Nutrition</option>
                                    <option value="5">HTN</option>
                                </select>
                            <label for="">Link imagen:</label>
                            <input required name="Img" type="text" class="form-control m-1">
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary mt-2">Guardar</button>
                <?php if (isset($msg)): ?>
                    <div class='alert alert-success' role='alert'>
                        <?= $msg ?>
                    </div>
                <?php endif; ?>
                </form>
                <ul class="list-group">
                    <?php foreach($products as $product):?>
                        <li class="list-group-item item-rutina">
                            <div class="m-2"></div>
                                <b> 
                                    <?=$product->Nombre?> 
                                    $<?=$product->Precio?>
                                </b>
                            </div>
                            <div class="actions col">
                                <a href="eliminar/<?=$product->ID?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                                <a href="#" type="button" class='btn btn-primary'><button type="submit" form="form" formaction="editar/<?=$product->ID?>">Editar</button></a>
                            </div>
                        </li>
                    <?php endforeach;?>
                </ul>
                <h3>Solo se puede modificar de a un campo</h3>
                <h6>(Coloque un valor donde quiere modificar y clique el campo que desea modificar)</h6>
            <?php include_once 'templates/footer.phtml';