<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?php echo (BASE_URL) ?>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="css/index.css">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
    </head>
            <?php include 'templates/header.phtml';?>
            <div class="posicion">
                <div class="container-login">
                        <form class="login-form" method="POST" action="auth">
                            <h1>Iniciar Sesión</h1>
                            <div class="form-group">
                                <label for="name">Nombre de usuario:</label>
                                <input type="text" id="username" name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Contraseña:</label>
                                <input type="password" id="password" name="password" required>
                            </div>
                            <?php if ($error): ?>
                                <div class='alert alert-danger' role='alert'>
                                    <?= $error ?>
                                </div>
                            <?php endif ?>
                            <button type="submit">Iniciar Sesión</button>       
                        </form>
                </div>
            </div>
            <?php include 'templates/footer.phtml';?>
        